### ISSUE TITLE
New bot syntax es6

### ISSUE THREAD

**Issue by sebastianjnuwu** [LMS5413/Ticket#4]
Eu criei um bot de tickets mais limpo assim utilizando o banco de dados mongo db ( bem mais organizado) eu fiz os teste e funciona ( não emplementei a geração da mensagem com select menu ) em es6 quer que eu contribua?

**Comment by LMS5413** [comment]
Esse projeto foi descontinuado. Você pode upar no seu github que posso deixar no README uma alternativa.
